# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 15, 8, 20, 951297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 15, 8, 20, 952051, tzinfo=utc)),
        ),
    ]
