# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 07:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170814_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 7, 22, 47, 217909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 7, 22, 47, 218568, tzinfo=utc)),
        ),
    ]
