# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170815_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 8, 36, 23, 294743, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
